packages:
  - apps/*
  - packages/*
  - tools/*
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver
injectWorkspacePackages: true
strictDepBuilds: true
