packages:
  - apps/*
  - packages/*
  - tools/*
onlyBuiltDependencies:
  - '@sentry/cli'
  - argon2
  - esbuild
  - sharp

injectWorkspacePackages: true
strictDepBuilds: true

overrides:
  # Until: https://github.com/drizzle-team/drizzle-orm/issues/3067
  esbuild: ">= 0.25.0"