---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.4.2
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 12h
  values:
    alertmanager:
      enabled: true

    grafana:
      adminPassword: prom-operator

      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.noo.eu

        tls:
          - hosts:
            - grafana.noo.eu
            secretName: grafana-general-tls

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt

      persistence:
        enabled: true
        storageClassName: "zfs-manual"
        accessModes:
          - ReadWriteOnce
        size: 5Gi

    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false

        volumeClaimTemplate:
          spec:
            storageClassName: zfs-manual
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
