apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: noo-id
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 5m
  path: ./infra/flux-charts/noo-id
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system