# 1.3.1.1: Ensure AppArmor is installed
- name: Ensure AppArmor is installed
  apt:
    pkg:
      - apparmor
      - apparmor-utils
    state: present

# 1.3.1.2: Ensure AppArmor is enabled in the bootloader configuration
- name: Ensure AppArmor is enabled in the bootloader configuration
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="apparmor=1"'
  notify: Update GRUB
