# 1.6.1 Ensure /etc/motd, /etc/issue, and /etc/issue.net configured properly
- name: "Delete {{ item }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/motd
    - /etc/issue
    - /etc/issue.net
    - /etc/update-motd.d/10-uname

- name: "Install MOTD scripts"
  copy:
    src: "{{ item }}"
    dest: /etc/update-motd.d/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - 10-header
    - 20-legal
