# 2.4.1.2: Ensure permissions on /etc/crontab are configured
- name: Ensure permissions on {{ item }} are configured
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - /etc/crontab
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly

- name: Ensure permissions on /etc/cron.d are configured
  file:
    path: /etc/cron.d
    owner: root
    group: root
    mode: 0700

# 2.4.1.8: Ensure crontab is restricted to authorized users
- name: Ensure permissions on /etc/cron.allow
  file:
    path: /etc/cron.allow
    owner: root
    group: crontab
    mode: 0640
    state: touch

- name: Remove /etc/cron.deny
  file:
    path: /etc/cron.deny
    state: absent

# 2.4.2.1: Ensure at is restricted to authorized users
- name: Ensure permissions on /etc/at.allow
  file:
    path: /etc/at.allow
    owner: root
    group: daemon
    mode: 0640
    state: touch

