# 4.2.1: Ensure ufw is installed
- name: Ensure ufw is installed
  apt:
    name: ufw
    state: present

- name: Enable UFW and allow SSH from our private network
  ufw:
    rule: allow
    from: 10.0.0.0/8
    proto: tcp
    port: 22
    state: enabled
