# 5.2.3 Ensure sudo log file exists
- name: Ensure sudo log file exists
  copy:
    dest: /etc/sudoers.d/sudo_log_file
    owner: root
    group: root
    mode: 0440
    content: |
      Defaults logfile="/var/log/sudo.log"

# 5.2.7 Ensure access to the su command is restricted
- name: Ensure access to the su command is restricted (create sugroup)
  group:
    name: sugroup
    state: present

- name: Ensure access to the su command is restricted
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^auth\s+required\s+pam_wheel.so'
    line: 'auth required pam_wheel.so use_uid group=sugroup'
