- name: Join worker nodes to Kubernetes cluster
  hosts: nodes
  become: yes
  vars:
    kube_version: "1.32.2"
    control_plane_endpoint: "kube.internal.noo.eu:6443"

  pre_tasks:
    - name: Get kubeadm join command (to extract discovery-token-ca-cert-hash)
      command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: postgres-1.internal.noo.eu
      run_once: true
      changed_when: false

  roles:
    - role: kube-prep
    - role: kube-install
  
  tasks:
    - name: Obtain my private IP
      shell: host {{ inventory_hostname }} | awk '{print $4}'
      register: my_ip
      changed_when: false

    - name: Set --node-ip in kubelet configuration
      lineinfile:
        line: "KUBELET_EXTRA_ARGS=--node-ip={{ my_ip.stdout }}"
        regexp: "^KUBELET_EXTRA_ARGS="
        path: /etc/default/kubelet
        state: present

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Check if node is already joined (by checking kubelet.conf)
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join node to Kubernetes
      shell: "{{ join_command.stdout_lines[0] }}"

      register: join_result
      changed_when: "join_result.rc == 0"
      failed_when: "join_result.rc != 0"
      when: not kubelet_conf.stat.exists

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
