- hosts: all
  become: yes
  vars:
    kube_version: "1.32.2"
  tasks: []
  
- name: Upgrade the control plane packages
  hosts: kube-master
  become: yes

  roles:
    - role: kube-install

- name: Perform the control plane upgrade on a single control plane node
  hosts: kube-master[0]
  become: yes

  tasks:
    - name: Kubeadm upgrade apply
      command: kubeadm upgrade apply v{{ kube_version }} --yes
    
- name: Restart the kubelet on the control plane, one node at a time
  hosts: kube-master
  become: yes
  serial: 1

  tasks:
    - name: Restart the kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
        daemon_reload: yes
      ignore_errors: yes

    - name: Give the kubelet time to restart
      wait_for:
        port: 10250
        delay: 5
        timeout: 120

- name: Upgrade the worker nodes
  hosts: nodes
  become: yes

  roles:
    - role: kube-install

- name: Restart the kubelet on the worker nodes
  hosts: nodes
  become: yes
  serial: 1

  tasks:
    - name: "Upgrade the worker nodes"
      command: kubeadm upgrade node

    - name: "Restart the kubelet"
      service:
        name: kubelet
        state: restarted
        enabled: yes
        daemon_reload: yes
    
    - name: "Give the kubelet time to restart"
      wait_for:
        port: 10250
        delay: 5
        timeout: 120
