apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: noo-id-secrets
    namespace: noo-id
data:
    PAIRWISE_SALT: ENC[AES256_GCM,data:o8RRbnIlwnO/KnfSExW9mGRc+Q96ltPd3L+DVnJ80mZxuNCRu6ecuPSc0ioIGr36NP4pbSSAVELjaiwp,iv:vxOGvZhl9YNHunnfPKvoqb20scfM00Ahsh7JipHX88E=,tag:1AxKMzp8qpCJkNOku9B4zA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:1DQe78QMBXBhinAir7GmwEPlozJ+K/ewYPHkrg==,iv:mlJlXuEMN4NQ+ULsvWTU2M0U0qJGD8Es5EBGmYd4AP4=,tag:kMOk/LA02ukyEJTubBSlDw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zAPtU0XsOQI7QdDPyy9tkgymjYIhdipUS5DVDcg+hDo8GwMqT5AiD7Wtb//hT3C0ygl4UftIHs4=,iv:t4ljLpyul1H1HkrSAxDfBWVxZ3dfbcIZWvQR1I4f5eo=,tag:gnXNuTRp3JUqrG/w6u/Pkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10s3tu8k5jldyq2j76ehkq4gy7m8d075vjww9yzwa3szkj379y5jq263e3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQlJjUkFRT0RWQk1odlZV
            MlNIYm1ueEE3OVcvVk8rSUxPOTJwOU82QncwCnBLWnFLNmJFOTNCV1NiWTh2eVJ2
            R3dsKzNlQm5TMGswQjdDa01OS3NaOW8KLS0tIHRSN3pLUG9uaExTUDFOaXlNSTFh
            aklDbElzVkxwQ3JkeHhQMjJTdnV3NlEKPdmSXq/p2wSDTI75JavLu3dK6L/8WcxU
            kRjV1nH0b9sEu1k3zSiMLezhPJTdVue3c3lmHv1grdfFSATSKcISnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T08:17:13Z"
    mac: ENC[AES256_GCM,data:JLTLetIe+ZePlkr7P0TFBFXE2cGon3gNMvqxjdOesR6c52boc1DNfnJk7Q63T2M6+gIf9qrJ2ApzD4YsoFqlQ0/DpFMQKIE7gaHqAGOwG/MnX1a7FHF9Fc2lIB2TsOVn/etCN/fNOPqYhhOFA/wooqmZVvPE8C0n6yv66j3+wyw=,iv:TkKAbl/YKNmf1J2xQin1Xzw7Cgox6Ihw+s+4cDTtiFU=,tag:JmVFjsaynViQKpw9epsROA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
