apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 5m
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system