k8sServiceHost: kube.internal.noo.eu
k8sServicePort: 6443
kubeProxyReplacement: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

cni:
  # https://docs.cilium.io/en/v1.7/gettingstarted/cni-chaining-portmap/
  # Necessary for nginx-ingress
  chainingMode: "portmap"
  # Allow Cilium and Istio to coexist
  exclusive: false

socketLB:
  hostNamespaceOnly: "true"
