repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.17.0
    set:
      - name: crds.enabled
        value: true

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.1
    values:
      - ./nginx-ingress-values.yml

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.12.2
    values:
      - ./metrics-server-values.yml

  - name: prometheus-operator
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 70.4.2
    values:
      - ./prometheus-values.yml

  - name: cnpg
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    version: 0.23.2

  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.20.0
    wait: true

  - name: istiod
    chart: istio/istiod
    namespace: istio-system
    wait: true
    needs:
      - istio-base
    set:
      - name: profile
        value: ambient
  
  - name: istio-cni
    chart: istio/cni
    namespace: istio-system
    wait: true
    needs:
      - istio-base
    set:
      - name: profile
        value: ambient
  
  - name: ztunnel
    chart: istio/ztunnel
    namespace: istio-system
    wait: true
    needs:
      - istio-base
