
  # Hetzner S3-compatible object storage does not support encryption.
  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://noo-backups
  #     s3:
  #       bucket: noo-backups
  #       s3Credentials:
  #         accessKeyId:
  #           name: aws-creds
  #           key: ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: aws-creds
  #           key: ACCESS_SECRET_KEY
  #     data:
  #       compression: gzip
  #       encryption: AES256
  #     wal:
  #       compression: gzip
  #       encryption: AES256
  #   retentionPolicy: "30d"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: noo-main
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": noo-main
  podMetricsEndpoints:
  - port: metrics