apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-manual

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: tester
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /mnt/test
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
