apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-postgres-1
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "zfs-manual"
  local:
    path: /secure/pgdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - postgres-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-postgres-2
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "zfs-manual"
  local:
    path: /secure/pgdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - postgres-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-postgres-3
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "zfs-manual"
  local:
    path: /secure/pgdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - postgres-3

