apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: cni
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: ambient