name: Playwright Tests
on:
  push:
    branches: [ main ]
    paths:
      - 'id/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'id/**'
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: id
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.3
    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bun run playwright install --with-deps
    - name: Run Playwright tests
      run: bun run playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
